name = "stefanuk12/darklua"
version = "0.16.1"
description = "A command line tool that transforms Lua code"
authors = [
    "CompeyDev <hi@devcomp.xyz>",
    "jeparlefrancais <jeparlefrancais21@gmail.com>",
]
repository = "https://github.com/Stefanuk12/darklua/tree/pesde"
includes = ["init.luau", "README.md", "pesde.toml"]

[engines]
lune = ">=0.8.7"
pesde = "^0.6.0-rc.6"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
core = { name = "pesde/toolchainlib", version = "^0.1.12" }

[indices]
default = "https://github.com/pesde-pkg/index"
